package com.jaedaero.domain.marketreport.mapper;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.jaedaero.domain.marketreport.vo.DailyMarketReportSourceVo;
import java.io.InputStream;
import java.util.List;
import java.util.UUID;
import javax.sql.DataSource;
import org.apache.ibatis.builder.xml.XMLMapperBuilder;
import org.apache.ibatis.io.Resources;
import org.apache.ibatis.session.Configuration;
import org.apache.ibatis.session.SqlSessionFactory;
import org.h2.jdbcx.JdbcDataSource;
import org.mybatis.spring.SqlSessionFactoryBean;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.junit.jupiter.api.Test;

class MarketReportSourceMapperXmlValidationTest {

  @Test
  void sourceMapperXmlIsParsedByMyBatis() throws Exception {
    Configuration configuration = new Configuration();
    try (InputStream inputStream =
        Resources.getResourceAsStream("mapper/marketreport/DailyMarketReportSourceMapper.xml")) {
      assertNotNull(inputStream);
      new XMLMapperBuilder(
              inputStream,
              configuration,
              "mapper/marketreport/DailyMarketReportSourceMapper.xml",
              configuration.getSqlFragments())
          .parse();
    }

    assertTrue(
        configuration.hasStatement(
            "com.jaedaero.domain.marketreport.mapper.DailyMarketReportSourceMapper.insert"));
    assertTrue(
        configuration.hasStatement(
            "com.jaedaero.domain.marketreport.mapper.DailyMarketReportSourceMapper.findByReportId"));
    assertTrue(
        configuration.hasStatement(
            "com.jaedaero.domain.marketreport.mapper.DailyMarketReportSourceMapper.deleteByReportId"));
  }

  @Test
  void sourceMapperCrudBindsReportAndSourceFieldsAgainstHermeticInMemoryDatabase() throws Exception {
    JdbcDataSource dataSource = new JdbcDataSource();
    dataSource.setURL(
        "jdbc:h2:mem:market_report_source_"
            + UUID.randomUUID().toString().replace('-', '_')
            + ";MODE=MySQL;DB_CLOSE_DELAY=-1");
    createSchema(dataSource);

    SqlSessionFactory sqlSessionFactory = sqlSessionFactory(dataSource);
    SqlSessionTemplate sessionTemplate = new SqlSessionTemplate(sqlSessionFactory);
    DailyMarketReportSourceMapper mapper = sessionTemplate.getMapper(DailyMarketReportSourceMapper.class);

    mapper.insert(
        DailyMarketReportSourceVo.builder()
            .reportId(1L)
            .sourceOrder(2)
            .title("두 번째 출처")
            .url("https://example.org/second")
            .build());
    mapper.insert(
        DailyMarketReportSourceVo.builder()
            .reportId(1L)
            .sourceOrder(1)
            .title("첫 번째 출처")
            .url("https://example.com/first")
            .build());
    mapper.insert(
        DailyMarketReportSourceVo.builder()
            .reportId(2L)
            .sourceOrder(1)
            .title("다른 리포트 출처")
            .url("https://example.net/other")
            .build());

    List<DailyMarketReportSourceVo> sources = mapper.findByReportId(1L);
    assertEquals(2, sources.size());
    assertEquals(1, sources.get(0).getSourceOrder());
    assertEquals("첫 번째 출처", sources.get(0).getTitle());
    assertEquals("https://example.com/first", sources.get(0).getUrl());
    assertEquals(2, sources.get(1).getSourceOrder());
    assertEquals("두 번째 출처", sources.get(1).getTitle());
    assertEquals("https://example.org/second", sources.get(1).getUrl());

    assertEquals(2, mapper.deleteByReportId(1L));
    assertTrue(mapper.findByReportId(1L).isEmpty());
    assertEquals(1, mapper.findByReportId(2L).size());
  }

  private void createSchema(DataSource dataSource) {
    new JdbcTemplate(dataSource)
        .execute(
            """
            CREATE TABLE daily_market_report (
                report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
            )
            """);
    new JdbcTemplate(dataSource)
        .execute(
            """
            INSERT INTO daily_market_report (report_id) VALUES (1), (2)
            """);
    new JdbcTemplate(dataSource)
        .execute(
            """
            CREATE TABLE daily_market_report_source (
                source_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                report_id BIGINT NOT NULL,
                source_order SMALLINT NOT NULL,
                title VARCHAR(500) NOT NULL,
                url VARCHAR(2048) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_source_report FOREIGN KEY (report_id)
                    REFERENCES daily_market_report(report_id)
            )
            """);
  }

  private SqlSessionFactory sqlSessionFactory(DataSource dataSource) throws Exception {
    SqlSessionFactoryBean factoryBean = new SqlSessionFactoryBean();
    factoryBean.setDataSource(dataSource);
    factoryBean.setConfigLocation(new ClassPathResource("mybatis-config.xml"));
    factoryBean.setMapperLocations(
        new ClassPathResource("mapper/marketreport/DailyMarketReportSourceMapper.xml"));
    factoryBean.afterPropertiesSet();
    return factoryBean.getObject();
  }
}
